# Generated by Django 4.2.6 on 2023-10-24 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20200908_0458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='favorites',
            new_name='tags',
        ),
    ]
