# Generated by Django 4.2.6 on 2023-10-21 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('week2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='questtion',
            new_name='question',
        ),
    ]
